version: "3.9"
services:
  my-sql-container:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: start
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: nghiangunger
      MYSQL_PASSWORD: 020202001488
    volumes: # Volumes: data of database will be store in us PC
      - ./data/mysql:/var/lib/mysql